### ISSUE TITLE
Cannot update during an existing state transition

### ISSUE THREAD

**Issue by JenningsWu** [alvin-777/poi-plugin-poi-stats#4]
![2 _f39oc uqdb p mq1zu](https://cloud.githubusercontent.com/assets/6861365/9322568/d2018e98-4529-11e5-8b4e-bbfbc6a565bc.png)
![v3f azbwv_9togydj jy gl](https://cloud.githubusercontent.com/assets/6861365/9322569/dd45a5d2-4529-11e5-891d-8e2bbd8fc65a.png)

**Comment by alvin-777** [comment]
The NavBar is registered for the webview events 'did-start-loading' & 'did-stop-loading' to update its status icon.

When a normal link is clicked:
![image](https://cloud.githubusercontent.com/assets/13615512/9428888/316a3674-4a01-11e5-8494-ae8719345f2d.png)
Left hand side is the time in milliseconds. The page took 300+ ms to load. It works fine.

However, the link at the top of Poi Stats page involves some kind of redirection:
![image](https://cloud.githubusercontent.com/assets/13615512/9428906/cc874192-4a01-11e5-88e4-0d56ffd334e9.png)
Note the second 'did-start-loading' event was emitted almost at the same time of the first 'did-stop-loading' event. That means, it called setState() twice at the same time, and the second one failed because the render process hadn't finished rendering the changes caused by the first setState().

According to [this similar issue](http://stackoverflow.com/questions/31420402/why-does-this-error-exist-invariant-violation-cannot-update-during-an-existin), this issue here can be safely ignored.

I've done some workarounds, basically just mimicking the old isMounted() method, to avoid the error message and make the debug console clean.

There might be another option: use the Flux architecture. That'll be another story...

BTW, the new-window plugin has the same issue, and I suppose the main window too.
